"use strict";
exports.__esModule = true;
var product_1 = require("./product");
var pricingRules_1 = require("./pricingRules");
var checkout_1 = require("./checkout");
var main = function () {
    product_1.initialiseProducts();
    var checkout = new checkout_1.Checkout(pricingRules_1.readPricingRules());
    checkout.setCustomer('default');
    checkout.add("Classic Ad");
    checkout.add("Stand out Ad");
    checkout.add("Premium Ad");
    console.log('$', checkout.total());
    checkout.clear();
    checkout.setCustomer('SecondBite');
    checkout.add("Classic Ad");
    checkout.add("Classic Ad");
    checkout.add("Classic Ad");
    checkout.add("Premium Ad");
    console.log('$', checkout.total());
    checkout.clear();
    checkout.setCustomer('Axil Coffee Roasters');
    checkout.add("Stand out Ad");
    checkout.add("Stand out Ad");
    checkout.add("Stand out Ad");
    checkout.add("Premium Ad");
    console.log('$', checkout.total());
};
main();
